[tool.poetry]
name = "WorkLog"
version = "1.0.0"
description = ""
authors = ["jack l. <me@somewhere.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyinputplus = "^0.2.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
